@startuml
'https://plantuml.com/object-diagram

map 绿洲 {
熔炉 => 
地下 => 
冰层 => 
海洋 => 
云层 => 
太空 => 
}
map 熔炉 {
扭曲 =>
腐蚀 =>
焚铄 =>
熔炉星礁 =>
}

map 地下 {
迷雾峡谷=>
枢纽=>
彼岸=>
家园=>
堕落之喉=>
风暴峭壁=>
幽潭湿地=>
外隅=>
灰穴=>
新世界=>
}
map 冰层 {
永昼冰荒=>
迷雾之源=>
火舌之沼=>
磁晶星礁=>
}
map 海洋 {
潜渊星礁=>
}
map 云层 {
天际星礁=>
}
map 太空 {
异界星礁=>
}

map 熔炉星礁{
熔炉星核=>
}
map 磁晶星礁{
电晶森林=>
始源之泉=>
磁晶星核=>
}
map 潜渊星礁{
苗床=>
轮环=>
血蚀=>
空白=>
潜渊星核=>
}
map 天际星礁{
彩色泥沼=>
光影溪涧=>
幻影草原=>
全息森林=>
反射沙漠=>
电波镇=>
水色乡=>
涂鸦村=>
天际星核=>
}
map 异界星礁{
思维纹理=>
灵魂网络=>
心智波动=>
记忆痕迹=>
融合螺旋=>
梦境之涡=>
集合意识=>
异界星核=>
}

绿洲::熔炉 ---up-> 熔炉
绿洲::地下 -up--> 地下
绿洲::冰层 -right> 冰层
绿洲::海洋 -left-> 海洋
绿洲::云层 --> 云层
绿洲::太空 ---> 太空

熔炉::熔炉星礁 -->熔炉星礁
冰层::磁晶星礁 -->磁晶星礁
海洋::潜渊星礁 -->潜渊星礁
云层::天际星礁 -->天际星礁
太空::异界星礁 -->异界星礁


@enduml
