@startuml

!define ENTITY class 


skinparam ranksep 60
skinparam nodesep 60
skinparam linetype polyline
hide circle
skinparam classBackgroundColor #fff
skinparam classBorderColor #0066ff
ENTITY 自然获取 {
  + 采集
  + 战斗奖励
  + 拾取
}


ENTITY 矿物 {
 
}
ENTITY 生物质 {
 
}


自然获取 --> 矿物
自然获取 --> 生物质


ENTITY 分拣 {
  + 自动分拣 
  + 手动分拣
}

矿物 --> 分拣
生物质 --> 分拣

ENTITY 能源 {
  +游戏内货币
}
ENTITY 金属 {}
ENTITY 晶体 {}
ENTITY 泡沫 {}
ENTITY 宝石 {}
ENTITY 食材 {}
ENTITY 废料 {}

分拣 --> 能源
分拣 --> 金属
分拣 --> 晶体
分拣 --> 泡沫
分拣 --> 食材
分拣 --> 宝石
分拣 --> 废料
加工台 --> 废料
工坊 --> 废料

ENTITY 枢纽 {
  + 存入能源 增加bit
  + 支付bit 获得能源
}

能源 --> 枢纽 :存入
枢纽 --> 能源 :取出

宝石 --> 调色盘 :消耗


ENTITY 加工台 {
  + 初级加工
} 

ENTITY 点心屋 {
  + 制作
}
ENTITY 调色盘 {
  + 获得卡牌装饰
}
食材 --> 点心屋 :交给
金属 --> 加工台 :材料
晶体 --> 加工台 :材料
泡沫 --> 加工台 :材料
宝石 --> 加工台 :材料
能源 --> 加工台 :燃料

ENTITY 日用品 {
  + 事件消耗
}
ENTITY 食品 {
  + 维持生命
  + 事件消耗
}
ENTITY 零件 {}
ENTITY 工具 {}

点心屋 --> 食品 
加工台 --> 日用品 :加工
加工台 --> 零件  :加工
加工台 --> 工具  :加工

工具 --> 加工台 :提供更多加工种类
工具 --> 工坊 :提供更多加工种类

ENTITY 工坊 {
  + 高级加工
}
零件 --> 工坊 :材料

ENTITY 设备 {}  
ENTITY 机械 {}
ENTITY 集成电路 {}
ENTITY 仪器 {}


工坊 --> 机械   :加工
工坊 --> 集成电路  :加工
工坊 --> 设备   :加工
工坊 --> 仪器  :加工


ENTITY 稀有物质 {}
废料 -up-> 稀有物质  :原料
仪器 --> 稀有物质  :提炼

ENTITY 异次元门 {}

仪器 --> 异次元门  :装置
稀有物质 --> 异次元门  :消耗

ENTITY 终末事件4 {
  + 隐藏章节 蓝星
}
异次元门 -left-> 终末事件4:进入


ENTITY AI {}
集成电路 --> AI  :编程设计

ENTITY 终末事件2 {
  + 游戏崩溃 全部存档损坏
  + 进入里世界 最后的对决
  + 战胜后 修复存档
}
AI --> 终末事件2  :战胜全部AI

ENTITY 遗物 {}
机械 --> 遗物  :地图探索

ENTITY 终末事件1 {
  + 开启泰坦遗迹
}
遗物 --> 终末事件1  :获得全部遗物

ENTITY 纳米装置 {}
设备 --> 纳米装置  :做出全部设备获得
ENTITY 警告 {}
纳米装置 -up-> 警告  :不要打开ui
ENTITY 终末事件3 {
   + 游戏出现控制台
   + 全部ui变成乱码
   + 输入指令进入ui世界
}
警告 ---> 终末事件3  :打开ui
@enduml