@startmindmap

* 物品分类
** 原料  (Raw Materials)
*** 矿物  (Minerals)
**** 晶石  (Gem) 
**** 燃石球  （Ignite Sphere）
**** 液态火   (Liquid fire)
**** 艾米特 （Emythite）
**** 以瑟莱斯  (Etherex) 
**** 环素  (Mobius) 
**** 磁引丝 （Magnet Weave）
**** 金絮  （Aurific-silken）
**** 芳香锦 （Aromasilk）
**** 冰锦  (Cryosilk) 
**** 螺线冰  (Spiraline) 
**** 光玻  (Lumiglass) 
**** 蓝燃石  (Azufire) 
**** 热岩石  (Hermal Rocks)
**** 艾因石  (Aeinstone) 
**** 阿尔奇石  (Argetite) 
**** 均衡石 （Equilithe）
**** 星辰石  (Stellarite) 
**** 浮晶  （Drifteonite）
**** 准石  (Quasistone) 
**** 源核 （Corenium）
**** 水矿  (Hydroxite) 
**** 彩虹尘 （Rainbodium）
**** 琉璃沫 （Vitreglycerol）
**** 黑脂  (Black Resin) 
**** 雪糕泥 （Iceslush Mud）
**** 太阳露  (Solar Dewdrops) 
**** 雾霭球 （Mistorb）
**** 乳砂  (Microsands Emulsion) 
**** 热液泡沫  (Hydrothermal Foam) 
*** 生物质  (Biomass)
**** 块 （Block）
**** 蜂巢  (Hive) 
**** 双极子 （Bipole）
**** 巨口 （Eater）
**** 脉冲 （Pulsar）
**** 时钟  (Clock)
**** 滑翔机 （Glider）
**** 蚂蚁  (Ant) 
**** 橡子 （Acorn）
**** 蛇 （Snake）
**** 雪花  (Snow) 
**** 海绵 （Sponge）
**** 瓦片 （tile）
**** 蕨  (Fern)
**** 刺胞  (Cnidaria) 
**** 曼德博球  (Mandelbulb) 
**** 吸引子  (Attractor) 
**** 蝴蝶  (Butterfly) 
**** 富文本 （Rich Text）
**** 混沌之种  (Chao Seed) 
**** 噪点  （Noise）
**** 纠缠  （Entangled）
**** 图元  (Graphic Elements) 
**** 连接网  （web） 
**** 胶带   (tape)
**** 标识键  （key）
**** 针头  （needle）
**** 补丁  （patch）
**** 音符  (note) 
**** 猫因子 （cat meme）
**** 三体 （Three-Body）

** 材料  (Materials)
*** 能源  (Energy)
*** 金属  (Metals)
*** 晶体  (Crystals)
*** 泡沫  (Foam)
*** 宝石  (Gems)
*** 食材  (Ingredients)
*** 废料  (Waste)
** 加工品  (Processed)
*** 日用品  (Goods)
*** 食品  (Food)
*** 零件  (Components)
*** 工具  (Tools)
** 造物  (Aritifact)
*** 设备  (Devices)
*** 晶体管  (Transistor)
*** 机械  (Machinery)
*** 仪器  (Instruments)
@endmindmap
